spring.application.name=general-ledger-management-system
server.port=8083





# Default System Users
admin.username = ${ADMIN_USERNAME}
admin.password = ${ADMIN_PASSWORD}

control.username = ${CONTROL_USERNAME}
control.password = ${CONTROL_PASSWORD}

authorizer.username = ${AUTHORIZER_USERNAME}
authorizer.password = ${AUTHORIZER_PASSWORD}

creator.username = ${CREATOR_USERNAME}
creator.password = ${CREATOR_PASSWORD}







# Oracle Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Logging

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG


# JWT Configuration

app.jwt.secret=${JWT_SECRET}

app.jwt.expiration=${JWT_EXPIRATION}
app.jwt.refresh-expiration=${REFRESH_EXPIRATION}


# Swagger/OpenAPI Configuration

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method
