spring.application.name=general-ledger-management-system
server.port=8083


#app.jwt.secret=9a4f2c8d3e7b1a5c6e8f9d0a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u
#app.jwt.access-expiration= 900000 # 15 Minutes
#app.jwt.refresh-expiration= 86400000 # 24 Hours

#app.default-admin.password=DefaultAdminPass123!
#app.default-admin.email=admin@company.com

#TWILIO_ACCOUNT_SID=AC723b3e47a7a61113e9f2a531ff4a90af
#TWILIO_AUTH_TOKEN=eee1652d725a774c35cdfcbebebe6b48
#TWILIO_VERIFY_SERVICE_SID=VAcf91283d2a5732c3d429a4d509c23a48
#
#app.otp.expiration-minutes= 5






# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=glm
spring.datasource.password=glm123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Logging

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG


# JWT Configuration

app.jwt.secret=GLMSApplicationSecretKeyForJWTAuthentication2026SecureKey

app.jwt.expiration=86400000


# Swagger/OpenAPI Configuration

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method
